In [1]:
from selenium import webdriver as wb
import pandas as pd
import time
from konlpy.tag import Kkma
import numpy as np
kkma = Kkma()
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.model_selection import cross_val_score
tfidf = TfidfVectorizer()
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [2]:
#1페이지
driver = wb.Chrome()
driver.get("https://www.google.com/search?q=%EB%B9%84%ED%83%80%EB%AF%BCc+%EA%B2%B0%ED%95%8D%EC%A6%9D&hl=ko&sxsrf=ALeKk022K4r_voZGm-c35uqt26ab4C7Aeg:1625207783058&ei=57PeYPL8Ao-F0wSo4anoCQ&start=10&sa=N&ved=2ahUKEwiyjOHk4sPxAhWPwpQKHahwCp0Q8tMDegQIARA6&biw=1536&bih=754")

In [3]:
data1 = driver.find_elements_by_css_selector(".VwiC3b.yXK7lf.MUxGbd.yDYNvb.lyLwlc")

In [4]:
#2페이지
driver = wb.Chrome()
driver.get("https://www.google.com/search?q=%EB%B9%84%ED%83%80%EB%AF%BCc+%EA%B2%B0%ED%95%8D%EC%A6%9D&hl=ko&sxsrf=ALeKk033pYwlk8bhioaBv83w2QXNVs7wxw:1625208505432&ei=ubbeYI_iGYyK0AT__IzwBQ&start=10&sa=N&ved=2ahUKEwjPopu95cPxAhUMBZQKHX8-A14Q8tMDegQIARA6&biw=982&bih=754")

In [5]:
data2 = driver.find_elements_by_css_selector(".VwiC3b.yXK7lf.MUxGbd.yDYNvb.lyLwlc")

In [6]:
#3페이지
driver = wb.Chrome()
driver.get("https://www.google.com/search?q=%EB%B9%84%ED%83%80%EB%AF%BCc+%EA%B2%B0%ED%95%8D%EC%A6%9D&hl=ko&sxsrf=ALeKk02QoYKqNdKHcgijm1pz81jXHqYdwg:1625208715227&ei=i7feYLyXDZiS0gSoh6QQ&start=20&sa=N&ved=2ahUKEwj8iKCh5sPxAhUYiZQKHagDCQI4ChDy0wN6BAgBEDw&biw=982&bih=754")

In [7]:
data3 = driver.find_elements_by_css_selector(".VwiC3b.yXK7lf.MUxGbd.yDYNvb.lyLwlc")

In [8]:
#4페이지
driver = wb.Chrome()
driver.get("https://www.google.com/search?q=%EB%B9%84%ED%83%80%EB%AF%BCc+%EA%B2%B0%ED%95%8D%EC%A6%9D&hl=ko&sxsrf=ALeKk01GwrbNvyq_DdnaVqQvapDU4Qt0ng:1625208729207&ei=mbfeYOuBDJHj0ASzpZyQCw&start=30&sa=N&ved=2ahUKEwirsvWn5sPxAhWRMZQKHbMSB7I4FBDy0wN6BAgBED4&biw=982&bih=754")

In [9]:
data4 = driver.find_elements_by_css_selector(".VwiC3b.yXK7lf.MUxGbd.yDYNvb.lyLwlc")

In [10]:
#5페이지
driver = wb.Chrome()
driver.get("https://www.google.com/search?q=%EB%B9%84%ED%83%80%EB%AF%BCc+%EA%B2%B0%ED%95%8D%EC%A6%9D&hl=ko&sxsrf=ALeKk02qyHJa0KDuM0UwY9datDzTuGq6mA:1625208754771&ei=srfeYLO6LoqQr7wPlIyckAc&start=40&sa=N&ved=2ahUKEwiz24205sPxAhUKyIsBHRQGB3I4HhDy0wN6BAgBEEA&biw=982&bih=754")

In [11]:
data5 = driver.find_elements_by_css_selector(".VwiC3b.yXK7lf.MUxGbd.yDYNvb.lyLwlc")

In [12]:
data = data1+data2+data3+data4+data5

In [13]:
# VV, VA, NNG의 형태소만 토큰화
def myTokenizer2(text):
    d = pd.DataFrame(kkma.pos(text), columns=['morph','tag'])
    d.set_index('tag', inplace=True)
    if ('VV' in d.index) | ('VA' in d.index) | ('NNG' in d.index):
        labels = ['VV','VA','NNG']
        return d.loc[d.index.intersection(labels)].dropna()['morph'].values
    else :
        return []

In [14]:
tfidf = TfidfVectorizer(tokenizer = myTokenizer2)

In [15]:
test =[]
for i in range(len(data)):
    data[i] = data[i].text


In [16]:
for i in range(len(data)):
    tfidf.fit(data[i:i+1])
    data_list = list(tfidf.vocabulary_)
    a = ""
    for i in range(len(data_list)):
        a = data_list[i] +" "+a
    test.append(a)

C:\Users\38214\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:489: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"
C:\Users\38214\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:489: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"
C:\Users\38214\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:489: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"
C:\Users\38214\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:489: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"
C:\Users\38214\anaconda3\lib\site-packages\s

In [17]:
y_a = np.ones((1,25))
y_b = np.zeros((1,25))

In [18]:
y = np.ones((1,50))
y = y[0]

In [19]:
len(test)

38

In [20]:
X_train = test
y_train = np.ones((1,len(test)))
y_train = np.transpose(y_train)
#y = 테스트 갯수만큼 1짜리 데이터 프레임 생성

In [21]:
count = CountVectorizer()
count.fit(X_train)

CountVectorizer()

In [22]:
X_train = count.transform(X_train)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X_train,y_train,test_size=0.3,
                                                   random_state = 3)

In [24]:
X_train.shape

(26, 237)

In [25]:
y_train.shape

(26, 1)

In [26]:
from sklearn.ensemble import RandomForestClassifier
forest  = RandomForestClassifier()

In [27]:
svm_result = cross_val_score(forest, X_train, y_train, cv=5)
svm_result.mean()

C:\Users\38214\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\38214\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\38214\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\38214\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y wa

1.0

In [28]:
forest.fit(X_train, y_train)

<ipython-input-28-e0147d7dbc7c>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest.fit(X_train, y_train)


RandomForestClassifier()

In [29]:
forest.score(X_test, y_test)

1.0

In [30]:
reviews = ["입에서 피가나요"]

In [31]:
reviews_transform = count.transform(reviews)

In [32]:
forest.predict(reviews_transform)

array([1.])

## 모델

In [33]:
data = pd.read_excel("data/테이블.xlsx")

In [34]:
data

Unnamed: 0  1  2  결과  Unnamed: 4
0          NaN  1  1   1         NaN
1          NaN  1  2   2         NaN
2          NaN  1  3   3         NaN
3          NaN  2  1   4         NaN
4          NaN  2  2   5         NaN
5          NaN  2  3   6         NaN
6          NaN  3  1   7         NaN
7          NaN  3  2   8         NaN
8          NaN  3  3   9         NaN
9          NaN  4  1  10         NaN
10         NaN  4  2  11         NaN
11         NaN  4  3  12         NaN
12         NaN  5  1  13         NaN
13         NaN  5  2  14         NaN
14         NaN  5  3  15         NaN
15         NaN  6  1  16         NaN
16         NaN  6  2  17         NaN
17         NaN  6  3  18         NaN
18         NaN  7  1  19         NaN
19         NaN  7  2  20         NaN
20         NaN  7  3  21         NaN

In [35]:
X_train = data.iloc[:,1:3]
y_train = data.iloc[:,3]

In [36]:
X_train = pd.get_dummies(X_train)
#X_test = pd.get_dummies(X_test)

In [37]:
X_train.shape

(21, 2)

In [38]:
X_train

1  2
0   1  1
1   1  2
2   1  3
3   2  1
4   2  2
5   2  3
6   3  1
7   3  2
8   3  3
9   4  1
10  4  2
11  4  3
12  5  1
13  5  2
14  5  3
15  6  1
16  6  2
17  6  3
18  7  1
19  7  2
20  7  3

In [39]:
y_train.shape


(21,)

In [40]:
from sklearn.tree import DecisionTreeClassifier

In [41]:
tree = DecisionTreeClassifier(max_depth=10)

In [42]:
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=10)

In [43]:
tree.predict([[1,2]])

array([2], dtype=int64)

In [44]:
tree.score(X_train,y_train)

1.0

In [53]:
tree.predict(X_train)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21], dtype=int64)

## 플라스크

In [45]:
import pickle

In [46]:
with open("titanic_trained_tree_model.pkl",'wb') as f :
    pickle.dump(tree,f)

In [47]:
with open('titanic_column_name.pkl','wb') as f2 :
    pickle.dump(X_train.columns,f2)

In [52]:
with open('titanic_trained_tree_model.pkl', 'rb') as f :
    model = pickle.load(f)
model.predict(df)

array([1], dtype=int64)